-- Schema for CampusTalk MVP

create extension if not exists pgcrypto;

create table if not exists universities (
  id bigint generated by default as identity primary key,
  name text not null,
  domain text not null unique,
  logo_url text,
  state text,
  city text,
  created_at timestamptz default now()
);

create table if not exists profiles (
  id uuid references auth.users on delete cascade,
  username text,
  university_id bigint references universities(id),
  year smallint,
  degree text,
  verified boolean default false,
  created_at timestamptz default now(),
  primary key(id)
);

create table if not exists waiting_queue (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) unique,
  filters jsonb,
  created_at timestamptz default now()
);

create table if not exists sessions (
  id uuid default gen_random_uuid() primary key,
  user_a uuid references profiles(id),
  user_b uuid references profiles(id),
  uni_a bigint,
  uni_b bigint,
  started_at timestamptz default now(),
  ended_at timestamptz,
  status text default 'connecting'
);

create table if not exists signals (
  id uuid default gen_random_uuid() primary key,
  session_id uuid,
  from_user uuid,
  to_user uuid,
  payload jsonb,
  created_at timestamptz default now()
);

create table if not exists reports (
  id uuid default gen_random_uuid() primary key,
  reporter uuid,
  reported uuid,
  session_id uuid,
  reason text,
  created_at timestamptz default now()
);
